### ISSUE TITLE
config.get() and config.set() should return rejected promises instead of throwing errors

### ISSUE THREAD

**Issue by joelwallis** [dsafio/dsafio#6]
`config.get()` and `config.set()` currently throw errors when you pass incorrect parameters, but your interface is promise based. It doesn't make sense. We need to return rejected promises for failed operations instead of throwing errors.

**Comment by joelwallis** [comment]
Exact lines where the issue is present:

- https://github.com/dsafio/dsafio/blob/master/lib/config.js#L10
- https://github.com/dsafio/dsafio/blob/master/lib/config.js#L45

**Comment by CLUBMATEjka** [comment]
I'm on it
